idf_component_register(SRCS "app.cpp"
                       "hal/hal.cpp"
                       "apps/launcher/launcher.cpp"
                       "apps/settings/settings.cpp"
                       "apps/fan_control/fan_control.cpp"
                       "apps/app_startup_anim/app_startup_anim.cpp"
                       "assets/assets.cpp"
                       "assets/assets_loader.cpp"
                       "asset/_start_124X22_RGB565A8_124x22.c"
                       "asset/_1_RGB565A8_34x25.c"
                       "asset/_2_RGB565A8_34x26.c"
                       "asset/_3_RGB565A8_34x26.c"
                       "asset/_4_RGB565A8_34x26.c"
                       "asset/_5_RGB565A8_34x26.c"
                       "asset/_6_RGB565A8_34x26.c"
                       "asset/_Page1_RGB565A8_128x64.c"
                       INCLUDE_DIRS "./"
                       REQUIRES mooncake smooth_ui_toolkit lvgl app_button esp_timer ble_ota LovyanGFX
                       )