idf_component_register(SRCS "app.cpp"
                       "hal/hal.cpp"
                    #    "apps/launcher/launcher.cpp"
                       "apps/menu/menu.cpp"
                       "apps/menu/view/menu_view.cpp"
                       "apps/homepage/homepage.cpp"
                       "apps/homepage/view/homepage_view.cpp"
                       "apps/settings/settings.cpp"
                       "apps/settings/view/settings_view.cpp"
                       "apps/animation_test_app/app.cpp"
                       "apps/enjoy/enjoy.cpp"
                    #    "apps/fan_control/fan_control.cpp"
                       "apps/app_startup_anim/app_startup_anim.cpp"
                       "ui/transitions.cpp"
                       "ui/checkbox.cpp"
                       "assets/assets.cpp"
                       "assets/assets_loader.cpp"
                       "assets/fonts/lv_font_Gully_Bold_16.c"
                       "assets/fonts/lv_font_Gully_Bold_12.c"
                       "assets/images/_start_124X22_RGB565A8_124x22.c"
                       "assets/images/app_settings/_About_RGB565A8_34x26.c"
                       "assets/images/app_settings/_Detail_RGB565A8_34x26.c"
                       "assets/images/app_settings/_Emoji_RGB565A8_34x26.c"
                       "assets/images/app_settings/_Enjoy_RGB565A8_34x26.c"
                       "assets/images/app_settings/_Health_RGB565A8_34x26.c"
                       "assets/images/app_settings/_Quit_RGB565A8_34x26.c"
                       "assets/images/app_settings/_Setting_RGB565A8_34x26.c"
                       "assets/images/homepage/_HomePage_1_RGB565A8_128x64.c"
                       "assets/images/homepage/_HomePage_2_RGB565A8_128x64.c"
                       INCLUDE_DIRS "./"
                       REQUIRES mooncake smooth_ui_toolkit lvgl app_button esp_timer ble_ota LovyanGFX va_effects
                       )
